[build]
  base = "."
  publish = "./dist"
  command = "yarn build"

[build.environment]
  VUE_APP_API_URL = "https://api.aec.works"

[context.staging.environment]
  VUE_APP_API_URL = "https://aecworks-api-staging.herokuapp.com"



[[redirects]]
  from = "/sitemap.xml"
  to = "https://api.aec.works/sitemaps/sitemap.xml"
  status = 200
  force = true

[[redirects]]
  from = "/sitemaps/*"
  to = "https://api.aec.works/sitemaps/:splat"
  query = {p = ":p"}
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/"
  status = 200
  force = false
